<#
.SYNOPSIS
    Publish this project to a new GitHub repository.

.DESCRIPTION
    Runs pre-flight checks before anything leaves your machine: scans for
    credentials, checks file sizes against GitHub's limits, and shows you
    exactly what will be committed. Nothing is pushed until you confirm.

.EXAMPLE
    .\setup_repo.ps1 -DryRun
    Check everything, push nothing.

.EXAMPLE
    .\setup_repo.ps1 -Name my-capstone
    Create a private repo called my-capstone.

.EXAMPLE
    .\setup_repo.ps1 -Public
    Create a PUBLIC repo. Requires typing PUBLIC to confirm.

.NOTES
    Windows blocks .ps1 files by default. Run it like this:
        powershell -ExecutionPolicy Bypass -File .\setup_repo.ps1 -DryRun
#>

[CmdletBinding()]
param(
    [string]$Name = "",
    [switch]$Public,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

# Git writes warnings (line endings, hints) to stderr. Under
# $ErrorActionPreference='Stop', redirecting stderr turns those into fatal
# errors, so a harmless CRLF notice would kill the script. Route every git
# call through here instead.
function Invoke-Git {
    param([Parameter(ValueFromRemainingArguments = $true)]$GitArgs)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        & git @GitArgs 2>&1 | Out-Null
        return $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $prev
    }
}

function Write-Ok    { param($m) Write-Host "  ok   " -ForegroundColor Green  -NoNewline; Write-Host $m }
function Write-Warn  { param($m) Write-Host " warn  " -ForegroundColor Yellow -NoNewline; Write-Host $m }
function Write-Fail  { param($m) Write-Host " FAIL  " -ForegroundColor Red    -NoNewline; Write-Host $m }
function Write-Info  { param($m) Write-Host "       $m" }
function Write-Head  { param($m) Write-Host ""; Write-Host $m -ForegroundColor White }

# ------------------------------------------------------------------ setup
Set-Location -Path $PSScriptRoot
$Root = (Get-Location).Path
if ([string]::IsNullOrWhiteSpace($Name)) { $Name = Split-Path $Root -Leaf }
$Visibility = if ($Public) { "public" } else { "private" }

Write-Host "Publishing: $Name ($Visibility)" -ForegroundColor White
Write-Host "From: $Root"

$Problems = 0

# ------------------------------------------------------- 1. environment
Write-Head "1. Environment"

$gitCmd = Get-Command git -ErrorAction SilentlyContinue
if (-not $gitCmd) {
    Write-Fail "git is not installed."
    Write-Info ""
    Write-Info "Install it with either of these, then reopen your terminal:"
    Write-Info "    winget install --id Git.Git -e"
    Write-Info "  or download from https://git-scm.com/download/win"
    Write-Info ""
    Write-Info "The installer defaults are fine. Accept them all."
    exit 1
}
Write-Ok ("git " + ((git --version) -split ' ')[2])

if (-not (Test-Path "backend")) {
    Write-Fail "No backend\ folder here. Run this from the project root."
    Write-Info "You are in: $Root"
    exit 1
}
Write-Ok "backend\ found"

$HaveGh = $false
$ghCmd = Get-Command gh -ErrorAction SilentlyContinue
if ($ghCmd) {
    gh auth status 2>&1 | Out-Null
    if ($LASTEXITCODE -eq 0) {
        $HaveGh = $true
        $who = (gh api user --jq .login 2>$null)
        Write-Ok "GitHub CLI authenticated as $who"
    } else {
        Write-Warn "GitHub CLI installed but not logged in. Run: gh auth login"
    }
} else {
    Write-Warn "GitHub CLI not installed. Manual push instructions will be printed."
    Write-Info "Optional: winget install --id GitHub.cli -e"
}

# --------------------------------------------------------- 2. gitignore
Write-Head "2. .gitignore"

if (-not (Test-Path ".gitignore")) {
    @'
__pycache__/
*.pyc
.venv/
venv/
.pytest_cache/
.DS_Store
Thumbs.db
.env
*.key
*.pem

# Response cache is regenerated by scripts/warm_cache.py.
# fixtures/ IS committed - it is the offline demo.
backend/.cache/
'@ | Set-Content -Path ".gitignore" -Encoding ASCII
    Write-Ok "created .gitignore"
} else {
    Write-Ok ".gitignore already present"
}

if (-not (Test-Path ".gitattributes")) {
    @'
# Normalise line endings so Windows and macOS collaborators do not produce
# whole-file diffs against each other.
* text=auto eol=lf
*.ps1 text eol=crlf
*.bat text eol=crlf
*.sh  text eol=lf
*.png binary
*.gz  binary
*.zip binary
'@ | Set-Content -Path ".gitattributes" -Encoding ASCII
    Write-Ok "created .gitattributes (stops CRLF warnings)"
} else {
    Write-Ok ".gitattributes already present"
}

# ----------------------------------------------------- 3. credential scan
Write-Head "3. Credential scan"

$skipDirs = @('.git', '.venv', 'venv', '__pycache__', '.pytest_cache', 'node_modules')
$skipExt  = @('.png','.jpg','.jpeg','.gif','.gz','.zip','.tar','.pyc','.ico','.pdf','.exe','.dll')

function Test-Excluded {
    param($FullName)
    # Split on both separators so this behaves the same everywhere.
    $parts = $FullName -split '[\\/]'
    foreach ($d in $skipDirs) { if ($parts -contains $d) { return $true } }
    return $false
}

$scanFiles = Get-ChildItem -Path $Root -Recurse -File -Force -ErrorAction SilentlyContinue | Where-Object {
    (-not (Test-Excluded $_.FullName)) -and
    ($skipExt -notcontains $_.Extension.ToLower()) -and
    ($_.Length -le 5MB)
}

$patterns = @(
    @{ Label = "private key block";   Rx = 'BEGIN [A-Z ]*PRIVATE KEY' },
    @{ Label = "GitHub token";        Rx = '\bgh[pousr]_[A-Za-z0-9]{36}\b' },
    @{ Label = "AWS access key";      Rx = '\bAKIA[0-9A-Z]{16}\b' },
    @{ Label = "API secret key";      Rx = '\bsk-[A-Za-z0-9]{20,}\b' },
    @{ Label = "hardcoded credential"; Rx = '[a-z_]*(key|secret|password|passwd|token|credential)[a-z_]*\s*[=:]\s*["''][A-Za-z0-9_/+-]{16,}' }
)

$secretHits = 0
foreach ($p in $patterns) {
    $hits = $scanFiles | Select-String -Pattern $p.Rx -ErrorAction SilentlyContinue |
            Group-Object Path | ForEach-Object { $_.Group[0] }
    if ($hits) {
        Write-Fail ($p.Label + ":")
        foreach ($h in $hits) {
            $rel = $h.Path.Replace($Root, "").TrimStart("\", "/")
            $snippet = $h.Matches[0].Value
            if ($snippet.Length -gt 44) { $snippet = $snippet.Substring(0, 44) + "..." }
            Write-Info "    $rel  (line $($h.LineNumber))"
            Write-Info "      matched: $snippet"
            if ($rel -match '[\\/]data[\\/]') {
                Write-Info "      NOTE: this is a downloaded third-party dataset,"
                Write-Info "            so this is very likely a false positive."
            }
        }
        $secretHits++
    }
}

if (Test-Path ".env") {
    Write-Fail ".env file present - it is gitignored, but confirm it is not staged"
    $secretHits++
}

if ($secretHits -eq 0) {
    Write-Ok "no credentials detected"
} else {
    $Problems++
    Write-Warn "review the files above before continuing"
    Write-Warn "if you add a ransomware.live API key, put it in .env, never in config.py"
}

# --------------------------------------------------------- 4. file sizes
Write-Head "4. File sizes"

$big = 0
$allFiles = Get-ChildItem -Path $Root -Recurse -File -Force -ErrorAction SilentlyContinue | Where-Object {
    -not (Test-Excluded $_.FullName)
}

foreach ($f in $allFiles) {
    $rel = $f.FullName.Replace($Root, "").TrimStart("\")
    $mb  = [math]::Round($f.Length / 1MB, 1)
    if ($f.Length -gt 100MB) {
        Write-Fail "$rel is ${mb}MB - exceeds GitHub's 100MB hard limit"
        $big++; $Problems++
    } elseif ($f.Length -gt 50MB) {
        Write-Warn "$rel is ${mb}MB - GitHub warns above 50MB"
        $big++
    } elseif ($f.Length -gt 10MB) {
        Write-Info "$rel is ${mb}MB (fine, just noting it)"
    }
}
if ($big -eq 0) { Write-Ok "nothing over 50MB" }

$totalMb = [math]::Round((($allFiles | Measure-Object -Property Length -Sum).Sum) / 1MB, 1)
Write-Info "total repo size: ${totalMb}MB"

# ---------------------------------------------------- 5. data snapshots
Write-Head "5. Data snapshots"

foreach ($rel in @("backend\data\sanctioned_addresses_XBT.txt", "backend\data\ransomwhere.json")) {
    if (Test-Path $rel) {
        $lines = (Get-Content $rel -ErrorAction SilentlyContinue | Measure-Object -Line).Lines
        Write-Ok ((Split-Path $rel -Leaf) + " present ($lines lines)")
    } else {
        Write-Warn ((Split-Path $rel -Leaf) + " missing - run backend\scripts\refresh_data.py first")
    }
}

if ((Test-Path "backend\fixtures") -and (Get-ChildItem "backend\fixtures" -ErrorAction SilentlyContinue)) {
    Write-Ok "fixtures\ present - offline demo will work for whoever clones this"
} else {
    Write-Warn "fixtures\ is empty - run scripts\warm_cache.py before the demo"
}

# ------------------------------------------------------- 6. visibility
Write-Head "6. Visibility"

if ($Visibility -eq "public") {
    Write-Warn "This repo will be PUBLIC."
    Write-Warn "It redistributes OFAC and Ransomwhere data snapshots. Both are"
    Write-Warn "public datasets, but check each provider's terms if unsure."
    Write-Warn "Anything committed now stays in git history even if deleted later."
    Write-Host ""
    if ([Console]::IsInputRedirected) {
        Write-Fail "Public repos need interactive confirmation. Nothing was pushed."
        exit 1
    }
    $confirm = Read-Host "  Type PUBLIC to confirm"
    if ($confirm -cne "PUBLIC") {
        Write-Info "Cancelled. Re-run without -Public for a private repo."
        exit 0
    }
} else {
    Write-Ok "private repo - you can add Aum as a collaborator afterwards"
}

# ---------------------------------------------------------- 7. summary
Write-Head "7. What will be committed"

if (-not (Test-Path ".git")) { Invoke-Git init -q | Out-Null }
Invoke-Git add -A | Out-Null

$staged = @(git diff --cached --name-only 2>$null)
Write-Info "$($staged.Count) files"
$staged | Select-Object -First 25 | ForEach-Object { Write-Info "    $_" }
if ($staged.Count -gt 25) { Write-Info "    ... and $($staged.Count - 25) more" }

if ($DryRun) {
    Write-Head "Dry run - nothing pushed"
    if ($Problems -gt 0) {
        Write-Fail "$Problems issue(s) flagged above - fix them before publishing."
        exit 1
    }
    Write-Info "Everything above passed. Re-run without -DryRun to publish."
    exit 0
}

if ($Problems -gt 0) {
    Write-Host ""
    Write-Fail "$Problems issue(s) flagged above."
    if ([Console]::IsInputRedirected) {
        Write-Fail "Not running interactively, so stopping rather than guessing."
        Write-Info "Nothing was pushed."
        exit 1
    }
    $go = Read-Host "  Continue anyway? [y/N]"
    if ($go -notmatch '^[Yy]') { Write-Info "Stopped. Nothing was pushed."; exit 1 }
}

# ------------------------------------------------------------ 8. commit
Write-Head "8. Commit"

# From here on git talks to the network and prints progress and hints to
# stderr. None of that is fatal, so stop treating it as an error.
$ErrorActionPreference = 'Continue'

if (-not (git config user.name 2>$null))  { git config user.name  $env:USERNAME }
if (-not (git config user.email 2>$null)) { git config user.email "$env:USERNAME@users.noreply.github.com" }

Invoke-Git branch -M main | Out-Null

$noChanges = (Invoke-Git diff --cached --quiet) -eq 0
if ($noChanges) {
    Write-Ok "nothing new to commit"
} else {
    $msg = @"
Explainable ransomware wallet risk enrichment - backend

Rule-based Bitcoin address risk enrichment with per-signal explanations.
Ten detection rules across five categories, bounded counterparty traversal,
offline mode, and a frozen API contract shared with the frontend.
"@
    git commit -q -m $msg
    Write-Ok "committed"
}

# -------------------------------------------------------- 9. create/push
Write-Head "9. Create and push"

if ($HaveGh) {
    gh repo view $Name 2>&1 | Out-Null
    $exists = ($LASTEXITCODE -eq 0)

    if ($exists) {
        Write-Warn "a repo named $Name already exists on your account"
        $go = Read-Host "  Push to it anyway? [y/N]"
        if ($go -notmatch '^[Yy]') { Write-Info "Stopped."; exit 1 }
        $hasRemote = (Invoke-Git remote get-url origin) -eq 0
        if (-not $hasRemote) {
            $url = gh repo view $Name --json url --jq .url
            git remote add origin "$url.git"
        }
        git push -u origin main
    } else {
        $visFlag = "--$Visibility"
        gh repo create $Name $visFlag --source=. --remote=origin `
            --description "NYU CS4CS capstone: explainable ransomware wallet risk enrichment" --push
    }

    $repoUrl = gh repo view $Name --json url --jq .url
    Write-Host ""
    Write-Ok "published: $repoUrl"
    Write-Host ""
    Write-Info "Next:"
    Write-Info "  Add Aum:  gh repo add-collaborator $Name HIS_USERNAME --permission push"
    Write-Info "  Send him: $repoUrl/blob/main/backend/contract.md"
} else {
    Write-Host ""
    Write-Info "GitHub CLI unavailable, so finish these three steps by hand:"
    Write-Host ""
    Write-Info "  1. Create an empty repo at https://github.com/new"
    Write-Info "     Name: $Name    Visibility: $Visibility"
    Write-Info "     Do NOT let GitHub add a README, .gitignore, or license."
    Write-Host ""
    Write-Info "  2. Connect and push (replace YOUR_USERNAME):"
    Write-Info "       git remote add origin https://github.com/YOUR_USERNAME/$Name.git"
    Write-Info "       git push -u origin main"
    Write-Host ""
    Write-Info "  3. Add Aum under Settings -> Collaborators."
    Write-Host ""
    Write-Info "Your commit is already made, so those two commands are all that's left."
}