#!/usr/bin/env bash
#
# Publish this project to a new GitHub repository.
#
#   ./setup_repo.sh                          # private repo, name from folder
#   ./setup_repo.sh --name my-capstone       # choose the name
#   ./setup_repo.sh --public                 # PUBLIC - read the warning first
#   ./setup_repo.sh --dry-run                # check everything, push nothing
#
# Runs a set of pre-flight checks before anything leaves your machine:
# scans for credentials, checks file sizes against GitHub's limits, and shows
# you exactly what will be committed. Nothing is pushed until you confirm.

set -euo pipefail

REPO_NAME=""
VISIBILITY="private"
DRY_RUN=0

RED=$'\033[0;31m'; YEL=$'\033[0;33m'; GRN=$'\033[0;32m'; BLD=$'\033[1m'; OFF=$'\033[0m'

info()  { echo "  $*"; }
ok()    { echo "${GRN}  ok  ${OFF} $*"; }
warn()  { echo "${YEL} warn ${OFF} $*"; }
fail()  { echo "${RED} FAIL ${OFF} $*"; }
head1() { echo; echo "${BLD}$*${OFF}"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)    REPO_NAME="${2:-}"; shift 2 ;;
    --public)  VISIBILITY="public"; shift ;;
    --private) VISIBILITY="private"; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) fail "unknown option: $1"; exit 1 ;;
  esac
done

cd "$(dirname "$0")"
ROOT="$(pwd)"
[[ -z "$REPO_NAME" ]] && REPO_NAME="$(basename "$ROOT")"

echo "${BLD}Publishing: ${REPO_NAME}  (${VISIBILITY})${OFF}"
echo "From: $ROOT"

# ---------------------------------------------------------------- pre-flight
PROBLEMS=0

head1 "1. Environment"

if ! command -v git >/dev/null 2>&1; then
  fail "git is not installed"; exit 1
fi
ok "git $(git --version | awk '{print $3}')"

if [[ ! -d backend ]]; then
  fail "no backend/ directory here - run this from the project root"; exit 1
fi
ok "backend/ found"

HAVE_GH=0
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    HAVE_GH=1
    ok "GitHub CLI authenticated as $(gh api user --jq .login 2>/dev/null || echo '?')"
  else
    warn "GitHub CLI installed but not logged in - run: gh auth login"
  fi
else
  warn "GitHub CLI not installed - will print manual instructions instead"
fi

# ---------------------------------------------------------------- gitignore
head1 "2. .gitignore"

if [[ ! -f .gitignore ]]; then
  cat > .gitignore <<'EOF'
__pycache__/
*.pyc
.venv/
venv/
.pytest_cache/
.DS_Store
.env
*.key
*.pem

# Response cache is regenerated by scripts/warm_cache.py.
# fixtures/ IS committed - it is the offline demo.
backend/.cache/
EOF
  ok "created .gitignore"
else
  ok ".gitignore already present"
fi

# ---------------------------------------------------------------- secrets
head1 "3. Credential scan"

SCAN_FILES=$(git -C "$ROOT" ls-files --cached --others --exclude-standard 2>/dev/null || find . -type f -not -path './.git/*')

SECRET_HITS=0
check_pattern() {
  local pattern="$1" label="$2"
  local hits
  hits=$(echo "$SCAN_FILES" | while read -r f; do
    [[ -f "$f" ]] || continue
    case "$f" in *.png|*.jpg|*.gz|*.zip) continue ;; esac
    grep -liE "$pattern" "$f" 2>/dev/null || true
  done)
  if [[ -n "$hits" ]]; then
    fail "$label:"
    echo "$hits" | sed 's/^/         /'
    SECRET_HITS=$((SECRET_HITS + 1))
  fi
}

check_pattern 'BEGIN [A-Z ]*PRIVATE KEY'          "private key block"
check_pattern 'gh[pousr]_[A-Za-z0-9]{30,}'        "GitHub token"
check_pattern 'AKIA[0-9A-Z]{16}'                  "AWS access key"
check_pattern 'sk-[A-Za-z0-9]{20,}'               "API secret key"
check_pattern '[a-z_]*(key|secret|password|passwd|token|credential)[a-z_]*[[:space:]]*[=:][[:space:]]*["'"'"'][A-Za-z0-9_/+-]{16,}' "hardcoded credential"

if [[ -f .env ]]; then
  fail ".env file present - it is gitignored, but confirm it is not staged"
  SECRET_HITS=$((SECRET_HITS + 1))
fi

if [[ $SECRET_HITS -eq 0 ]]; then
  ok "no credentials detected"
else
  PROBLEMS=$((PROBLEMS + 1))
  warn "review the files above before continuing"
  warn "if you later add a ransomware.live API key, put it in .env, never in config.py"
fi

# ---------------------------------------------------------------- file sizes
head1 "4. File sizes"

BIG=0
while IFS= read -r f; do
  [[ -f "$f" ]] || continue
  SZ=$(wc -c < "$f" 2>/dev/null || echo 0)
  MB=$((SZ / 1048576))
  if [[ $SZ -gt 104857600 ]]; then
    fail "${f} is ${MB}MB - exceeds GitHub's 100MB hard limit"
    BIG=$((BIG + 1)); PROBLEMS=$((PROBLEMS + 1))
  elif [[ $SZ -gt 52428800 ]]; then
    warn "${f} is ${MB}MB - GitHub warns above 50MB"
    BIG=$((BIG + 1))
  elif [[ $SZ -gt 10485760 ]]; then
    info "${f} is ${MB}MB (fine, just noting it)"
  fi
done <<< "$SCAN_FILES"

[[ $BIG -eq 0 ]] && ok "nothing over 50MB"

TOTAL=$(du -sh --exclude=.git --exclude=.venv --exclude=__pycache__ . 2>/dev/null | cut -f1 || echo "?")
info "total repo size: ${TOTAL}"

# ---------------------------------------------------------------- data check
head1 "5. Data snapshots"

for f in backend/data/sanctioned_addresses_XBT.txt backend/data/ransomwhere.json; do
  if [[ -f "$f" ]]; then
    ok "$(basename "$f") present ($(wc -l < "$f" 2>/dev/null || echo '?') lines)"
  else
    warn "$(basename "$f") missing - run backend/scripts/refresh_data.py first"
  fi
done

if [[ -d backend/fixtures ]] && [[ -n "$(ls -A backend/fixtures 2>/dev/null)" ]]; then
  ok "fixtures/ present - offline demo will work for whoever clones this"
else
  warn "fixtures/ is empty - run scripts/warm_cache.py before the demo"
fi

# ---------------------------------------------------------------- visibility
head1 "6. Visibility"

if [[ "$VISIBILITY" == "public" ]]; then
  warn "This repo will be ${BLD}PUBLIC${OFF}."
  warn "It redistributes OFAC and Ransomwhere data snapshots. Both are public"
  warn "datasets, but check each provider's terms if you are unsure."
  warn "Anything you commit now stays in the git history even if deleted later."
  echo
  read -r -p "  Type PUBLIC to confirm: " CONFIRM
  if [[ "$CONFIRM" != "PUBLIC" ]]; then
    info "Cancelled. Re-run without --public for a private repo."
    exit 0
  fi
else
  ok "private repo - you can add Aum as a collaborator afterwards"
fi

# ---------------------------------------------------------------- summary
head1 "7. What will be committed"

git init -q 2>/dev/null || true
git add -A 2>/dev/null || true

FILE_COUNT=$(git diff --cached --name-only 2>/dev/null | wc -l | tr -d ' ')
info "${FILE_COUNT} files"
git diff --cached --name-only 2>/dev/null | head -25 | sed 's/^/         /'
[[ "$FILE_COUNT" -gt 25 ]] && info "... and $((FILE_COUNT - 25)) more"

if [[ $DRY_RUN -eq 1 ]]; then
  head1 "Dry run - nothing pushed"
  if [[ $PROBLEMS -gt 0 ]]; then
    fail "${PROBLEMS} issue(s) flagged above - fix them before publishing."
    exit 1
  fi
  info "Everything above passed. Re-run without --dry-run to publish."
  exit 0
fi

if [[ $PROBLEMS -gt 0 ]]; then
  echo
  fail "${PROBLEMS} issue(s) flagged above."
  if [[ ! -t 0 ]]; then
    fail "Not running interactively, so stopping rather than guessing. Nothing pushed."
    exit 1
  fi
  read -r -p "  Continue anyway? [y/N] " GO
  [[ "$GO" =~ ^[Yy]$ ]] || { info "Stopped. Nothing was pushed."; exit 1; }
fi

# ---------------------------------------------------------------- commit
head1 "8. Commit"

git config user.name  >/dev/null 2>&1 || git config user.name  "$(whoami)"
git config user.email >/dev/null 2>&1 || git config user.email "$(whoami)@users.noreply.github.com"

git branch -M main 2>/dev/null || true

if git diff --cached --quiet 2>/dev/null; then
  ok "nothing new to commit"
else
  git commit -q -m "Explainable ransomware wallet risk enrichment - backend

Rule-based Bitcoin address risk enrichment with per-signal explanations.
Ten detection rules across five categories, bounded counterparty traversal,
offline mode, and a frozen API contract shared with the frontend."
  ok "committed"
fi

# ---------------------------------------------------------------- push
head1 "9. Create and push"

if [[ $HAVE_GH -eq 1 ]]; then
  if gh repo view "$REPO_NAME" >/dev/null 2>&1; then
    warn "a repo named ${REPO_NAME} already exists on your account"
    read -r -p "  Push to it anyway? [y/N] " GO
    [[ "$GO" =~ ^[Yy]$ ]] || { info "Stopped."; exit 1; }
    git remote get-url origin >/dev/null 2>&1 || \
      git remote add origin "$(gh repo view "$REPO_NAME" --json sshUrl --jq .sshUrl)"
    git push -u origin main
  else
    gh repo create "$REPO_NAME" \
      --"$VISIBILITY" \
      --source=. \
      --remote=origin \
      --description "NYU CS4CS capstone: explainable ransomware wallet risk enrichment" \
      --push
  fi
  URL=$(gh repo view "$REPO_NAME" --json url --jq .url)
  echo
  ok "published: ${URL}"
  echo
  info "Next:"
  info "  Add Aum:   gh repo add-collaborator ${REPO_NAME} HIS_USERNAME --permission push"
  info "  Send him:  ${URL}/blob/main/backend/contract.md"
else
  echo
  info "GitHub CLI unavailable, so finish these three steps by hand:"
  echo
  info "  1. Create an empty repo at https://github.com/new"
  info "     Name: ${REPO_NAME}   Visibility: ${VISIBILITY}"
  info "     Do NOT let GitHub add a README, .gitignore, or license."
  echo
  info "  2. Connect and push:"
  info "       git remote add origin git@github.com:YOUR_USERNAME/${REPO_NAME}.git"
  info "       git push -u origin main"
  echo
  info "  3. Add Aum under Settings -> Collaborators."
  echo
  info "Your commit is already made, so those two commands are all that's left."
fi
